Repository cloudcomputinginha/interview_be, pull requests merged in 2025-06, with the labels that each got.

#20 ✨ [CCI-20] 이력서 세부 조회, 리스트 조회 API
  src/main/java/cloudcomputinginha/demo/converter/ResumeConverter.java
  src/main/java/cloudcomputinginha/demo/repository/ResumeRepository.java
  src/main/java/cloudcomputinginha/demo/service/ResumeQueryService.java
  src/main/java/cloudcomputinginha/demo/service/ResumeQueryServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/ResumeRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/ResumeResponseDTO.java
  src/main/resources/insert_dummy_data.sql
Labels: :sparkles: feature

#22 ✨[CCI-26] 면접 생성 API
  .DS_Store
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/cloudcomputinginha/.DS_Store
  src/main/java/cloudcomputinginha/demo/apiPayload/code/handler/CoverletterHandler.java
  src/main/java/cloudcomputinginha/demo/apiPayload/code/handler/MemberHandler.java
  src/main/java/cloudcomputinginha/demo/converter/InterviewConverter.java
  src/main/java/cloudcomputinginha/demo/domain/Interview.java
  src/main/java/cloudcomputinginha/demo/domain/InterviewOption.java
  src/main/java/cloudcomputinginha/demo/domain/enums/InterviewFormat.java
  src/main/java/cloudcomputinginha/demo/domain/enums/InterviewType.java
  src/main/java/cloudcomputinginha/demo/domain/enums/StartType.java
  src/main/java/cloudcomputinginha/demo/domain/enums/VoiceType.java
  src/main/java/cloudcomputinginha/demo/repository/InterviewOptionRepository.java
  src/main/java/cloudcomputinginha/demo/service/InterviewCommandService.java
  src/main/java/cloudcomputinginha/demo/service/InterviewCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/InterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewRequestDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewResponseDTO.java
  src/main/resources/insert_dummy_data.sql
Labels: :sparkles: feature

#25 ✨ [CCI-29] 면접 시작 API
  src/main/java/cloudcomputinginha/demo/converter/InterviewConverter.java
  src/main/java/cloudcomputinginha/demo/converter/InterviewOptionConverter.java
  src/main/java/cloudcomputinginha/demo/converter/MemberInterviewConverter.java
  src/main/java/cloudcomputinginha/demo/converter/ResumeConverter.java
  src/main/java/cloudcomputinginha/demo/repository/MemberInterviewRepository.java
  src/main/java/cloudcomputinginha/demo/repository/QnaRepository.java
  src/main/java/cloudcomputinginha/demo/service/InterviewCommandService.java
  src/main/java/cloudcomputinginha/demo/service/InterviewCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/InterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/CoverletterResponseDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewOptionResponseDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewResponseDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/MemberInterviewResponseDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/ResumeResponseDTO.java
  src/main/resources/insert_dummy_data.sql
Labels: :sparkles: feature

#26 ✨[CCI-34] 일대다 면접 모집글 조회 API
  src/main/java/cloudcomputinginha/demo/converter/InterviewConverter.java
  src/main/java/cloudcomputinginha/demo/repository/InterviewQueryRepository.java
  src/main/java/cloudcomputinginha/demo/repository/InterviewQueryRepositoryImpl.java
  src/main/java/cloudcomputinginha/demo/service/InterviewQueryService.java
  src/main/java/cloudcomputinginha/demo/service/InterviewQueryServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/InterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewRequestDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewResponseDTO.java
Labels: :sparkles: feature

#27 [CCI-38] CORS 설정 및 Spring Security 관련 의존성 추가
  build.gradle
  src/main/java/cloudcomputinginha/demo/config/SecurityConfig.java
Labels: :sparkles: feature

#29 ✨[CCI-35] 일대다 면접 모집글 세부 조회 API
  src/main/java/cloudcomputinginha/demo/converter/InterviewConverter.java
  src/main/java/cloudcomputinginha/demo/service/InterviewQueryService.java
  src/main/java/cloudcomputinginha/demo/service/InterviewQueryServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/InterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewResponseDTO.java
Labels: :sparkles: feature

#32 ✨[CCI-32] 면접 수정 API
  src/main/java/cloudcomputinginha/demo/apiPayload/code/status/ErrorStatus.java
  src/main/java/cloudcomputinginha/demo/converter/InterviewConverter.java
  src/main/java/cloudcomputinginha/demo/domain/Interview.java
  src/main/java/cloudcomputinginha/demo/service/InterviewCommandService.java
  src/main/java/cloudcomputinginha/demo/service/InterviewCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/InterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewRequestDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewResponseDTO.java
Labels: :sparkles: feature

#34 ✨[CCI-33] 면접 옵션 수정 API
  src/main/java/cloudcomputinginha/demo/converter/InterviewOptionConverter.java
  src/main/java/cloudcomputinginha/demo/domain/InterviewOption.java
  src/main/java/cloudcomputinginha/demo/service/InterviewOptionCommandService.java
  src/main/java/cloudcomputinginha/demo/service/InterviewOptionCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/InterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewOptionRequestDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewOptionResponseDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewResponseDTO.java
Labels: :sparkles: feature

#36 🐛[CCI-41]: S3 Put PresignedUrl API 수정
  src/main/java/cloudcomputinginha/demo/service/S3PresignedService.java
Labels: :bug: bug, ✅ test

#38 ✨[CCI-24] 나의 면접 리스트 조회(페이징 X)
  .gitignore
  src/main/java/cloudcomputinginha/demo/converter/InterviewConverter.java
  src/main/java/cloudcomputinginha/demo/converter/InterviewOptionConverter.java
  src/main/java/cloudcomputinginha/demo/converter/MemberInterviewConverter.java
  src/main/java/cloudcomputinginha/demo/domain/Interview.java
  src/main/java/cloudcomputinginha/demo/repository/MemberInterviewRepository.java
  src/main/java/cloudcomputinginha/demo/service/MemberInterviewCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/service/MemberInterviewQueryService.java
  src/main/java/cloudcomputinginha/demo/service/MemberInterviewQueryServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/InterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/controller/MemberInterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewOptionResponseDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewResponseDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/MemberInterviewResponseDTO.java
  src/main/resources/insert_dummy_data.sql
Labels: :sparkles: feature

#39 [CCI-43] Socket을 통한 면접 대기실 입장, 퇴장 구현, Quartz 의존성을 활용한 면접 자동 시작 구현, AOP 기반 로거 도입
  .github/ISSUE_TEMPLATE/custom.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  gradlew
  src/main/java/cloudcomputinginha/demo/apiPayload/code/handler/SocketErrorHandler.java
  src/main/java/cloudcomputinginha/demo/apiPayload/code/status/ErrorStatus.java
  src/main/java/cloudcomputinginha/demo/aspect/ExceptionLoggingAspect.java
  src/main/java/cloudcomputinginha/demo/aspect/MethodLoggingAspect.java
  src/main/java/cloudcomputinginha/demo/aspect/RestExceptionLoggingAspect.java
  src/main/java/cloudcomputinginha/demo/aspect/websocket/WebSocketConnectionLogger.java
  src/main/java/cloudcomputinginha/demo/aspect/websocket/WebSocketExceptionLoggingAspect.java
  src/main/java/cloudcomputinginha/demo/aspect/websocket/WebSocketMessageLoggingAspect.java
  src/main/java/cloudcomputinginha/demo/config/SecurityConfig.java
  src/main/java/cloudcomputinginha/demo/config/WebSocketConfig.java
  src/main/java/cloudcomputinginha/demo/converter/MemberInterviewSocketMessageConverter.java
  src/main/java/cloudcomputinginha/demo/infra/messaging/WaitingRoomEventPublisher.java
  src/main/java/cloudcomputinginha/demo/repository/InterviewRepository.java
  src/main/java/cloudcomputinginha/demo/repository/MemberInterviewRepository.java
  src/main/java/cloudcomputinginha/demo/scheduler/InterviewScheduleInitializer.java
  src/main/java/cloudcomputinginha/demo/scheduler/InterviewScheduler.java
  src/main/java/cloudcomputinginha/demo/scheduler/job/InterviewSchedulerJob.java
  src/main/java/cloudcomputinginha/demo/service/InterviewCommandService.java
  src/main/java/cloudcomputinginha/demo/service/InterviewCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/service/MemberInterviewCommandService.java
  src/main/java/cloudcomputinginha/demo/service/MemberInterviewCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/service/MemberInterviewSocketService.java
  src/main/java/cloudcomputinginha/demo/service/MemberInterviewSocketServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/InterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/controller/MemberInterviewRestController.java
  src/main/java/cloudcomputinginha/demo/web/controller/MemberInterviewSocketController.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewRequestDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/MemberInterviewSocketMessageDTO.java
  src/main/java/cloudcomputinginha/demo/web/session/InMemorySessionManager.java
  src/main/java/cloudcomputinginha/demo/web/session/InterviewWaitingRoomSessionManager.java
  src/main/java/cloudcomputinginha/demo/web/session/SessionManager.java
Labels: :sparkles: feature

#40 ✅ [CCI-50] 인터뷰 현재 참가인원 동시성 테스트
  src/test/java/cloudcomputinginha/demo/domain/InterviewTest.java
Labels: ✅ test

#42 ✨[CCI-16] 소셜 로그인 및 로그아웃 구현 API
  build.gradle
  src/main/java/cloudcomputinginha/demo/config/auth/JwtAuthenticationFilter.java
  src/main/java/cloudcomputinginha/demo/config/auth/JwtProvider.java
  src/main/java/cloudcomputinginha/demo/config/auth/SecurityConfig.java
  src/main/java/cloudcomputinginha/demo/config/auth/controller/OauthController.java
  src/main/java/cloudcomputinginha/demo/config/auth/converter/OauthConverter.java
  src/main/java/cloudcomputinginha/demo/config/auth/domain/GoogleUser.java
  src/main/java/cloudcomputinginha/demo/config/auth/service/GoogleOauth.java
  src/main/java/cloudcomputinginha/demo/config/auth/service/GoogleUserInfoClient.java
  src/main/java/cloudcomputinginha/demo/config/auth/service/OauthService.java
  src/main/java/cloudcomputinginha/demo/config/auth/service/SocialOauth.java
  src/main/java/cloudcomputinginha/demo/domain/Member.java
  src/main/java/cloudcomputinginha/demo/repository/MemberRepository.java
Labels: :sparkles: feature

#46 ✨[CCI-53] 토큰 재발급 API
  src/main/java/cloudcomputinginha/demo/config/auth/JwtProvider.java
  src/main/java/cloudcomputinginha/demo/config/auth/controller/OauthController.java
  src/main/java/cloudcomputinginha/demo/config/auth/dto/TokenReissueRequestDto.java
  src/main/java/cloudcomputinginha/demo/config/auth/dto/TokenReissueResponseDto.java
Labels: :sparkles: feature

#48 [ CCI-46] SSE 알림 전송 로직 수정
  src/main/java/cloudcomputinginha/demo/config/AsyncConfig.java
  src/main/java/cloudcomputinginha/demo/infra/ApplicationEventPublisher.java
  src/main/java/cloudcomputinginha/demo/service/notification/NotificationCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/service/notification/NotificationSseServiceImpl.java
  src/main/java/cloudcomputinginha/demo/service/notification/event/NotificationEvent.java
Labels: :bug: bug

#50 ✨[CCI-18] 사용자 기본 정보 등록 API
  src/main/java/cloudcomputinginha/demo/domain/Member.java
  src/main/java/cloudcomputinginha/demo/service/member/MemberCommandService.java
  src/main/java/cloudcomputinginha/demo/service/member/MemberCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/MemberRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/MemberInfoRequestDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/MemberInfoResponseDTO.java
Labels: :sparkles: feature

#51 ✨[CCI-59] 사용자 기본 정보 변경 API
  src/main/java/cloudcomputinginha/demo/config/auth/SecurityConfig.java
  src/main/java/cloudcomputinginha/demo/converter/MemberConverter.java
  src/main/java/cloudcomputinginha/demo/domain/Member.java
  src/main/java/cloudcomputinginha/demo/service/member/MemberCommandService.java
  src/main/java/cloudcomputinginha/demo/service/member/MemberCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/web/controller/MemberRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/MemberInfoRequestDTO.java
Labels: :sparkles: feature
