Repository cloudcomputinginha/interview_be, pull requests merged in 2025-08, with the labels that each got.

#62 fix : ec2 small -> micro로 변경되면서 발생하는 actuator error 해결
  build.gradle
Labels: :bug: bug

#64 [CCI-72] 면접 생성 에러 해결
  src/main/java/cloudcomputinginha/demo/service/interview/InterviewCommandServiceImpl.java
Labels: :bug: bug

#65 ✨[CCI-63] AI 서버 OCR 연결
  build.gradle
  src/main/java/cloudcomputinginha/demo/DemoApplication.java
  src/main/java/cloudcomputinginha/demo/apiPayload/code/handler/AiHandler.java
  src/main/java/cloudcomputinginha/demo/apiPayload/code/status/ErrorStatus.java
  src/main/java/cloudcomputinginha/demo/config/AiFeignConfig.java
  src/main/java/cloudcomputinginha/demo/config/DomainInfo.java
  src/main/java/cloudcomputinginha/demo/config/S3Config.java
  src/main/java/cloudcomputinginha/demo/config/auth/SecurityConfig.java
  src/main/java/cloudcomputinginha/demo/config/properties/CloudProperties.java
  src/main/java/cloudcomputinginha/demo/config/properties/DomainProperties.java
  src/main/java/cloudcomputinginha/demo/converter/NotificationConverter.java
  src/main/java/cloudcomputinginha/demo/converter/ResumeConverter.java
  src/main/java/cloudcomputinginha/demo/domain/Interview.java
  src/main/java/cloudcomputinginha/demo/domain/Notification.java
  src/main/java/cloudcomputinginha/demo/domain/Resume.java
  src/main/java/cloudcomputinginha/demo/domain/embedded/DomainUrl.java
  src/main/java/cloudcomputinginha/demo/domain/enums/NotificationType.java
  src/main/java/cloudcomputinginha/demo/infra/ai/AiOpenFeignService.java
  src/main/java/cloudcomputinginha/demo/infra/ai/AiServiceErrorDecoder.java
  src/main/java/cloudcomputinginha/demo/infra/aws/ResumeS3Service.java
  src/main/java/cloudcomputinginha/demo/preprocessor/NotificationPreprocessor.java
  src/main/java/cloudcomputinginha/demo/scheduler/job/InterviewReminderJob.java
  src/main/java/cloudcomputinginha/demo/service/memberInterview/MemberInterviewCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/service/notification/NotificationCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/service/resume/ResumeCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/validation/annotation/ValidS3Url.java
  src/main/java/cloudcomputinginha/demo/validation/validator/S3UrlValidator.java
  src/main/java/cloudcomputinginha/demo/web/controller/ResumeRestController.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewRequestDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/ResumeRequestDTO.java
  src/main/java/cloudcomputinginha/demo/web/dto/ResumeResponseDTO.java
Labels: :sparkles: feature

#66 ✨[CCI-75] 면접 바로 실행 시 스케쥴 취소 실패 에러 해결(+면접 생성/면접 시작 코드 리팩토링)
  src/main/java/cloudcomputinginha/demo/apiPayload/code/status/ErrorStatus.java
  src/main/java/cloudcomputinginha/demo/config/auth/SecurityConfig.java
  src/main/java/cloudcomputinginha/demo/converter/InterviewConverter.java
  src/main/java/cloudcomputinginha/demo/domain/Interview.java
  src/main/java/cloudcomputinginha/demo/repository/InterviewRepository.java
  src/main/java/cloudcomputinginha/demo/service/interview/InterviewCommandService.java
  src/main/java/cloudcomputinginha/demo/service/interview/InterviewCommandServiceImpl.java
  src/main/java/cloudcomputinginha/demo/service/memberInterview/MemberInterviewSocketService.java
  src/main/java/cloudcomputinginha/demo/web/dto/InterviewRequestDTO.java
Labels: :bug: bug, :recycle: refactor
